name: CI - Build
on:
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: npm ci 🚀
        run: npm ci --prefer-offline --no-audit --ignore-scripts

      - name: Format and Build
        run: npm run all

      # Taken from https://github.com/actions/reusable-workflows/blob/main/.github/workflows/check-dist.yml
      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol ${{inputs.folder-path}} | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after the build. See the status below:"
            git diff
            exit 1
          fi
        id: diff

      # If inners of the dist directory were different than expected, upload the expected version as an artifact
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{inputs.dist-path}}
