name: CI - Increment Version on Merge
on:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
      - 'action.yml'

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    uses: ./.github/workflows/build.yml

  tests:
    uses: ./.github/workflows/tests.yml

  increment-version:
    needs: [build, tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # See https://github.com/im-open/git-version-lite for more details around how to increment major/minor/patch through commit messages
      - name: Increment the version
        uses: im-open/git-version-lite@v2.2.0
        id: version
        with:
          create-ref: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-release-type: major

      - name: Create Major and Latest Tags
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.version.outputs.NEXT_VERSION_SHA }}
          source-tag: ${{ steps.version.outputs.NEXT_VERSION }}
          include-major: true
          include-latest: true
